INSERT INTO ROLE(ID,ROLE_NAME) values (1,'ADMIN');
INSERT INTO ROLE(ID,ROLE_NAME) values (2,'USER');

INSERT INTO APP_USR(ID,USERNAME,PASSWORD,IS_ACTIVE,EMAIL,CRE_TS) VALUES (1,'mfedirko','abc123',TRUE,'mfedirko@ex.com',CURRENT_DATE());
INSERT INTO APP_USR(ID,USERNAME,PASSWORD,IS_ACTIVE,EMAIL,CRE_TS) VALUES (2,'otheruser','def123',TRUE,'ok@ex.com',CURRENT_DATE());

INSERT INTO APP_USR_ROLES values (1,1);
INSERT INTO APP_USR_ROLES values (1,2);
INSERT INTO APP_USR_ROLES values (2,2);